killermike: move to single mqtt connection

diff --git a/gateway/sensors-collect b/gateway/sensors-collect
--- a/gateway/sensors-collect
+++ b/gateway/sensors-collect
@@ -9,10 +9,19 @@ TOPIC=sensors/killermike
 [ -n "$MQTTPASS" ] || { echo "export MQTT password as MQTTPASS" >&2 ; exit 1 ; }
 [ -n "$MQTTHOST" ] || { echo "export MQTT server as MQTTHOST" >&2 ; exit 1 ; }
 
-# arguments: topic (key), message. swallow errors so we don't exit.
+# swallow errors so we don't exit. no arguments.
+mqttflush() {
+  "$MQTT" --id killermike -h "$MQTTHOST" -t "$TOPIC" -m "{$POST}" -u "$MQTTUSER" -P "$MQTTPASS" || \
+    { echo "error publishing to mqtt: $POST" >&2 ; }
+}
+
+# arguments: topic (key), message.
 mqtt() {
-  "$MQTT" --id killermike -h "$MQTTHOST" -t "$TOPIC" -m "{\"$1\":$2}" -u "$MQTTUSER" -P "$MQTTPASS" || \
-    { echo "error publishing $1 to mqtt" >&2 ; }
+  if [ -z "$POST" ] ; then
+    POST="\"$1\":$2"
+  else
+    POST="$POST, \"$1\":$2"
+  fi
 }
 
 # prints bytes RX from a /proc/net/dev line provided as $*
@@ -31,6 +40,7 @@ procnetdevtx() {
 CHIPID=nct6798-isa-0290
 
 while true ; do
+  POST=""
   # this moves around; find it dynamically
   if [ -z "$AMDGPU" ] ; then
     AMDGPU=$(sensors | grep ^amdgpu-pci) || echo "Couldn't find AMD GPU" >&2
@@ -68,5 +78,6 @@ while true ; do
   LOAD=$(cut -d\  -f1 < /proc/loadavg)
   mqtt loadavg $LOAD
 
+  mqttflush
   sleep 15
 done
