workstation: move disk and sensors-collect to single connection

diff --git a/workstation/disk-collect b/workstation/disk-collect
--- a/workstation/disk-collect
+++ b/workstation/disk-collect
@@ -8,13 +8,23 @@ TOPIC=sensors/schwarzgerät
 [ -n "$MQTTUSER" ] || { echo "export MQTT username as MQTTUSER" >&2 ; exit 1 ; }
 [ -n "$MQTTPASS" ] || { echo "export MQTT password as MQTTPASS" >&2 ; exit 1 ; }
 
-# arguments: topic (key), message. swallow errors so we don't exit.
+# swallow errors so we don't exit. no arguments.
+mqttflush() {
+  "$MQTT" --id schwarzgerät -t "$TOPIC" -m "{$POST}" -u "$MQTTUSER" -P "$MQTTPASS" || \
+    { echo "error publishing to mqtt: $POST" >&2 ; }
+}
+
+# arguments: topic (key), message.
 mqtt() {
-  "$MQTT" --id schwarzgerät -t "$TOPIC" -m "{\"$1\":$2}" -u "$MQTTUSER" -P "$MQTTPASS" || \
-    { echo "error publishing to mqtt" >&2 ; }
+  if [ -z "$POST" ] ; then
+    POST="\"$1\":$2"
+  else
+    POST="$POST, \"$1\":$2"
+  fi
 }
 
 while true ; do
+  POST=""
   # SATA disks
   DISKTEMPS=$(sensors -j | jq '.[]|select(.Adapter|test("SCSI adapter"))|.sata.temp1_input')
   DIDX=0
@@ -43,5 +53,6 @@ while true ; do
     mqtt "$NAME" $PCENT
   done
 
+  mqttflush
   sleep 15
 done
diff --git a/workstation/sensors-collect b/workstation/sensors-collect
--- a/workstation/sensors-collect
+++ b/workstation/sensors-collect
@@ -9,10 +9,19 @@ TOPIC=sensors/schwarzgerät
 [ -n "$MQTTUSER" ] || { echo "export MQTT username as MQTTUSER" >&2 ; exit 1 ; }
 [ -n "$MQTTPASS" ] || { echo "export MQTT password as MQTTPASS" >&2 ; exit 1 ; }
 
-# arguments: topic (key), message. swallow errors so we don't exit.
+# swallow errors so we don't exit. no arguments.
+mqttflush() {
+  "$MQTT" --id schwarzgerät -t "$TOPIC" -m "{$POST}" -u "$MQTTUSER" -P "$MQTTPASS" || \
+    { echo "error publishing to mqtt: $POST" >&2 ; }
+}
+
+# arguments: topic (key), message.
 mqtt() {
-  "$MQTT" --id schwarzgerät -t "$TOPIC" -m "{\"$1\":$2}" -u "$MQTTUSER" -P "$MQTTPASS" || \
-    { echo "error publishing $1 to mqtt" >&2 ; }
+  if [ -z "$POST" ] ; then
+    POST="\"$1\":$2"
+  else
+    POST="$POST, \"$1\":$2"
+  fi
 }
 
 # prints bytes RX from a /proc/net/dev line provided as $*
@@ -29,6 +38,7 @@ procnetdevtx() {
 #mqtt kernelver "\"`uname -r`\""
 
 while true ; do
+  POST=""
   if [ -z "$HFLOW" ] ; then
     HFLOW=$(sensors | grep ^highflownext-hid) || echo "Couldn't find Aquacomputer highflow NEXT" >&2
   fi
@@ -164,5 +174,6 @@ while true ; do
   UPSEC=$(cut -d\  -f1 < /proc/uptime)
   mqtt uptimesec $UPSEC
 
-  sleep 10
+  mqttflush
+  sleep 15
 done
