[mic] preserve accuracy through averaging operation

diff --git a/workstation/geiger-collect b/workstation/geiger-collect
--- a/workstation/geiger-collect
+++ b/workstation/geiger-collect
@@ -29,9 +29,9 @@ do
       GSAMPS=0
     fi
   elif echo "$line" | grep '^Mic: ' > /dev/null ; then
-    { M=$((M + VAL)) && MSAMPS=$((MSAMPS + 1)) ; } || { echo "Invalid mic report: $VAL" >&2 ; }
+    { M=`jq -n $M+$VAL` && MSAMPS=$((MSAMPS + 1)) ; } || { echo "Invalid mic report: $VAL" >&2 ; }
     if [ $MSAMPS -ge 15 ] ; then
-      VAL=$(echo "$M / $MSAMPS" | bc)
+      VAL=`jq -n $M/$MSAMPS`
       "$MQTT" -u "$MQTTUSER" -P "$MQTTPASS" -t "$TOPIC/mic" -m "{\"mic\":$VAL}" || \
         { echo "Error publishing mic sample" >&2 ; }
       M=0
