workstation/power-collect: move to single mqtt connection

diff --git a/workstation/power-collect b/workstation/power-collect
--- a/workstation/power-collect
+++ b/workstation/power-collect
@@ -8,10 +8,19 @@ TOPIC=sensors/schwarzgerät
 [ -n "$MQTTUSER" ] || { echo "export MQTT username as MQTTUSER" >&2 ; exit 1 ; }
 [ -n "$MQTTPASS" ] || { echo "export MQTT password as MQTTPASS" >&2 ; exit 1 ; }
 
-# arguments: topic (key), message. swallow errors so we don't exit.
+# swallow errors so we don't exit. no arguments.
+mqttflush() {
+  "$MQTT" --id schwarzgerät -t "$TOPIC" -m "{$POST}" -u "$MQTTUSER" -P "$MQTTPASS" || \
+    { echo "error publishing to mqtt: $POST" >&2 ; }
+}
+
+# arguments: topic (key), message.
 mqtt() {
-  "$MQTT" --id schwarzgerät -t "$TOPIC" -m "{\"$1\":$2}" -u "$MQTTUSER" -P "$MQTTPASS" || \
-    { echo "error publishing to mqtt" >&2 ; }
+  if [ -z "$POST" ] ; then
+    POST="\"$1\":$2"
+  else
+    POST="$POST, \"$1\":$2"
+  fi
 }
 
 isnumber() {
@@ -22,6 +31,7 @@ isnumber() {
 }
 
 while true ; do
+  POST=""
   # these require root, ugh--set powercap-info suid root, or something similar =\.
   UPSW=$(pwrstat -status | grep Load | cut -d\  -f2 || echo "")
   if [ -n "$UPSW" ] ; then
@@ -61,6 +71,7 @@ while true ; do
     fi
   fi
 
+  mqttflush
   sleep 15
 
 done
