amoled: move to single mqtt connection

diff --git a/pi/amoled-collect b/pi/amoled-collect
--- a/pi/amoled-collect
+++ b/pi/amoled-collect
@@ -9,22 +9,30 @@ MQTTHOST=10.128.0.1
 [ -n "$MQTTUSER" ] || { echo "export MQTT username as MQTTUSER" >&2 ; exit 1 ; }
 [ -n "$MQTTPASS" ] || { echo "export MQTT password as MQTTPASS" >&2 ; exit 1 ; }
 
-# arguments: topic (key), message. swallow errors so we don't exit.
+# swallow errors so we don't exit. no arguments.
+mqttflush() {
+  "$MQTT" --id amoled -h "$MQTTHOST" -t "$TOPIC" -m "{$POST}" -u "$MQTTUSER" -P "$MQTTPASS" || \
+    { echo "error publishing to mqtt: $POST" >&2 ; }
+}
+
+# arguments: topic (key), message.
 mqtt() {
-  "$MQTT" --id amoled -h "$MQTTHOST" -t "$TOPIC" -m "{\"$1\":$2}" -u "$MQTTUSER" -P "$MQTTPASS" || \
-    { echo "error publishing to mqtt" >&2 ; }
+  if [ -z "$POST" ] ; then
+    POST="\"$1\":$2"
+  else
+    POST="$POST, \"$1\":$2"
+  fi
 }
 
 while true ; do
+  POST=""
   # rpi temp sensor
   TCTL=$(sensors -j | jq '."cpu_thermal-virtual-0".temp1.temp1_input') 2> /dev/null
-  "$MQTT" -h "$MQTTHOST" -t "$TOPIC" -m "{\"rpi4temp\":$TCTL}" -u "$MQTTUSER" -P "$MQTTPASS" \
-    || { echo "Failed publishing to MQTT" >&2 ; }
+  mqtt rpi4temp $TCTL
 
   # rpi voltage
   PIVOLTS=$(vcgencmd measure_volts | cut -d= -f2 | cut -dV -f1)
-  "$MQTT" -h "$MQTTHOST" -t "$TOPIC" -m "{\"rpi4volts\":$PIVOLTS}" -u "$MQTTUSER" -P "$MQTTPASS" \
-    || { echo "Failed publishing to MQTT" >&2 ; }
+  mqtt rpi4volts $PIVOLTS
 
   UPSEC=$(cut -d\  -f1 < /proc/uptime)
   mqtt uptimesec $UPSEC
@@ -36,5 +44,6 @@ while true ; do
   DBM=$(iw dev wlan0 link | grep signal | cut -d: -f2- | cut -dd -f1 | tr -d [:space:])
   mqtt signaldbm $DBM
 
+  mqttflush
   sleep 15
 done
